name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  basic-sanity:
    name: basic-sanity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify demo files exist
        run: |
          test -f README.md
          test -f demo.txt
